---
- hosts: localhost
  user: root
  pre_tasks:
    - name: be sure apt cache is updated
      apt: update_cache=yes

  vars:
    domjudge_api_endpoint: http://some-endpoint.example.com/api
    domjudge_api_endpoint_user: judgehost
    domjudge_api_endpoint_pass: judgehost_pass
    domjudge_repo: 'deb http://domjudge.org/debian unstable/'
    domjudge_repo_key: 'http://domjudge.org/repokey.asc'

  tasks:
    # pre-reqs for apt_repository
    - name: install pre-requisites
      apt: pkg={{ item }} state=present
      with_items:
        - python-pycurl
        - python-apt
      tags: domjudge-judgehost

    - name: debconf seed judgehost setup
      debconf: name='{{ item['name'] }}' question='{{ item['question'] }}' value='{{ item.value }}' vtype='{{ item.type }}'
      tags: domjudge-judgehost
      with_items:
          - name: domjudge-judgehost
            question: 'domjudge/api_endpoint'
            value: "{{ domjudge_api_endpoint }}"
            type: password
          - name: domjudge-judgehost
            question: 'domjudge/api_endpoint_user'
            value: "{{ domjudge_api_endpoint_user }}"
            type: string
          - name: domjudge-judgehost
            question: 'domjudge/api_endpoint_pass'
            value: "{{ domjudge_api_endpoint_pass }}"
            type: string

    - name: add signing key for the domjudge packages
      apt_key: url={{ domjudge_repo_key }} state=present

    - name: add the official domjudge repository
      apt_repository: repo="{{ domjudge_repo }}" update_cache=yes state=present
      tags: domjudge-judgehost

    - name: install the domjudge judgehost
      apt: pkg=domjudge-judgehost state=latest install_recommends=no
      tags: domjudge-judgehost
      register: installdj

    - name: Make sure domjudge isn't running
      service: name=domjudge-judgehost state=stopped
      when: installdj.changed

    - name: delete existing judgehost init scripts
      command: /usr/sbin/update-rc.d -f domjudge-judgehost remove removes=/etc/rc0.d/K20domjudge-judgehost
    - name: delete old init script
      file: path=/etc/init.d/domjudge-judgehost state=absent

    - name: install our own init scripts
      copy: src=files/{{item}} dest=/etc/init/{{item}}
      with_items:
        - judgedaemon-instance.conf
        - judgedaemons.conf

    - name: enable swap accounting(for cgroups)
      lineinfile: dest=/etc/default/grub.d/50-cloudimg-settings.cfg regexp="^GRUB_CMDLINE_LINUX_DEFAULT=" line='GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 swapaccount=1"' state=present
      notify: update grub

    - name: install debootstrap which is used when making the chroot
      apt: pkg=debootstrap state=latest
      tags: domjudge-judgehost

    - name: setup the chroot
      script: files/make_chroot /var/lib/domjudge/javachroot/ creates=/var/lib/domjudge/javachroot/
      tags: domjudge-judgehost
      environment:
        DEBMIRROR: http://us-east-1.ec2.archive.ubuntu.com/ubuntu

    - name: debconf accept java license
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
      tags: java

    - name: be sure webupd8team ppa is available
      apt_repository: repo='ppa:webupd8team/java' update_cache=yes state=present
      tags: java

    - name: install compilers
      apt: pkg={{ item }} state=present
      with_items:
        - build-essential           # c/c++
        - ghc                       # haskell
        - fpc                       # pascal
        - python                    # python 2.7
        - python3                   # python 3
        - gnat                      # gnu ada
        - gfortran                  # fortran
        - mono-complete             # c#
        #- fsharp                    # fsharp
        - lua5.2                    # lua
        #- oracle-java7-installer   # java7
        - oracle-java8-installer    # java8
        - gccgo                     # go reference compiler
        - golang                    # go using gcc
        - ruby                      # ruby
        - nodejs                    # javascript
        - gdc                       # D

    - name: check for scala
      stat: path=/usr/bin/scala
      register: has_scala
    - name: get scala deb file
      get_url: url=http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.deb dest=/tmp/scala.deb
      when: not has_scala.stat.exists
    - name: install scala
      apt: deb=/tmp/scala.deb
      when: not has_scala.stat.exists

    - name: do something with ufw
      ufw: logging=off
      tags: ['domjudge-judgehost', 'ufw']

  handlers:
    - name: update grub
      command: /usr/sbin/update-grub
